#!/usr/bin/env node
/**
 * Generates src/version.ts from package.json version.
 * Run before TypeScript compilation to bake version into the build.
 */

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

const packageJson = JSON.parse(readFileSync(join(rootDir, 'package.json'), 'utf8'));
const versionTs = `// Auto-generated by scripts/build-version.js - DO NOT EDIT
export const VERSION = '${packageJson.version}';\n`;

writeFileSync(join(rootDir, 'src', 'version.ts'), versionTs);
console.error(`Generated src/version.ts with version ${packageJson.version}`);
